### ISSUE TITLE
Allow functions to take data frames instead of individual vectors

### ISSUE THREAD

**Issue by austinj** [jepusto/scdhlm#2]
Obviously, not an urgent issue, but taking a data frame as the first argument and then specifying variable names instead of needing to pass individual vectors for each argument would make these functions easier to manipulate.

**Comment by austinj** [comment]
Apologies; by "these functions," I mean `effect_size_MB()` and `effect_size_ABk()`.

**Comment by jepusto** [comment]
See http://adv-r.had.co.nz/Computing-on-the-language.html for techniques to address this.

**Comment by jepusto** [comment]
```
data(Saddler)

Saddler_quality <- subset(Saddler, measure=="writing quality")

# current usage
effect_size_MB(Saddler_quality$outcome, Saddler_quality$treatment,
               Saddler_quality$case, Saddler_quality$time)

# what we want:
effect_size_MB(data = Saddler_quality,
               outcome = outcome,
               treatment = treatment,
               id = case,
               time = time)
```

**Comment by jepusto** [comment]
Make sure to include a unit test.
