### ISSUE TITLE
Blank plot for nonexistent cases

### ISSUE THREAD

**Issue by manchen07** [jepusto/scdhlm#20]
- Fix the blank plot.

- Fix the order of students in the graph.

After selecting school 1 in Bryant 2018, the graph should plot data from 6 students (student 1 to student 6). But it now includes students that are not in school 1 (i.e., student 10, student 11) and plots them as blank (shown below). And the order is not perfect: student 1, student 10, student 11, student 2...

![image (1)](https://user-images.githubusercontent.com/58210618/78836354-883e9400-79b7-11ea-8af7-8d4a10c6dd41.png)

**Comment by jepusto** [comment]
@manchen07 could you please check if this issue still occurs in the app if you open it from within RStudio (i.e., by running `shine_SCD()`). If the error doesn't occur, then please close the issue.
