### ISSUE TITLE
Web-app: Add warning when dataset includes less than three cases.

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#22]
Add a check for the number of cases in a loaded dataset. Display a warning in one or more tabs of the calculator if the dataset includes less than three cases.

**Comment by bethanyhamilton** [comment]
Should I use modal dialogs for the warning message? [https://shiny.rstudio.com/articles/modal-dialogs.html]

**Comment by bethanyhamilton** [comment]
Should I use modal dialogs for the warning message? [](https://shiny.rstudio.com/articles/modal-dialogs.html)

**Comment by jepusto** [comment]
Sure!
