### ISSUE TITLE
Vignette alignment with Pustejovsky et al (2014)

### ISSUE THREAD

**Issue by austinj** [jepusto/scdhlm#37]
Quick background: I'd like to use `g_mlm()` for a meta-analysis. Since there are multiple studies, I'm going to need to specify models for each of them individually. As I work through how to correctly specify these models, I've been relying on Pustejovsky et al (2014) and the `scdhlm` documentation. I noticed that the [vignette's specifications for MB4](https://github.com/jepusto/scdhlm/blob/67e4058392ecc7a8efe97c477de188433a37789e/vignettes/Estimating-effect-sizes.Rmd#L228) don't match those from [Pustejovsky et al. (2014, see bottom of page 377)](https://github.com/jepusto/scdhlm/files/4899123/Pustejovsky.et.al.2014.-.Design-Comparable.Effect.Sizes.in.Multiple.Baseline.Designs.-.A.General.Modeling.Framework.pdf). If this is a misinterpretation of mine regarding how these models are specified, and not something else, I apologize!

**Comment by jepusto** [comment]
This is a syntax difference between g_mlm() and the older g_REML() function. When I first designed the package, I wrote g_REML() to follow PHS (2014). But we recently updated the package to handle a (much) broader class of multilevel models with the g_mlm() function. In doing so, we had to change the specification of the r_const argument to align with how variance component parameters are arranged in lme() models. 

The nice thing about the updated syntax is that it is easier to understand which entry in r_const corresponds to which variance component. You can use the function `extract_varcomp` to pull out the estimated variance components:
```
extract_varcomp(hlm2)

extract_varcomp(hlm2) %>% unlist() # to see a vector instead of a list with multiple entries
```
The resulting list will be in the same order that is used for r_const. So, for the MB4 specification that you pointed out, we need the first and the last entry of the variance components, thus `r_const = c(1, 0, 0, 0, 1)`.

**Comment by jepusto** [comment]
I'll add a footnote to the vignette entries to clarify this.

**Comment by austinj** [comment]
Great; I appreciate the prompt support you’ve been able to provide, James. Thank you.

**Comment by jepusto** [comment]
[The vignette](http://jepusto.github.io/scdhlm/articles/Estimating-effect-sizes.html) is now updated. See footnotes 1 and 2.
