### ISSUE TITLE
Open shiny app with a dataset

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#41]
If possible, revise `shine_scd()` so that it can take a dataset as an input argument. If specified, open the app with those arguments already set.

**Comment by manchen07** [comment]
Does the following link help?
https://stackoverflow.com/questions/44999615/passing-parameters-into-shiny-server/48831832#48831832

Once allowing `shine_scd()` to take a dataset as an input argument, the app will open with the dataset already loaded. Do we still need to specify study design, choose case, phase, session, and outcome variable, and specify baseline and treatment level after running the app? Or do you want to set study design, etc as input arguments in `shine_scd()`? If latter, once those arguments are specified, the "Load" tab will be completely removed from the app.

**Comment by jepusto** [comment]
Yes, I think the link provides a good pattern to follow. 

Let's start by just passing the dataset input argument, and then setting everything else dynamically in the app. But the idea would be to make the inputs __optional__. So if you call
```
shine_scd()
```
the app would open as it currently does, but if you call
```
shine_scd(data = <dataset>)
```
the app would open with `<dataset>` already loaded, still on the "Load" tab.

**Comment by jepusto** [comment]
Closed by d042c14215aae6ef3712ec23b15f185546e774c8
