### ISSUE TITLE
Create user-facing data-preprocessing function

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#46]
Make an exported function `preprocess_SCD()` that handles all of the initial data-cleaning steps currently executed in the app. This will make the server code simpler and will also simplify the R syntax generated by the app. Function skeleton:
```
preprocess_SCD <- function(data, case, phase, session, design = c("MB","TR"), round_session = TRUE) {
}
```
This function can then replace the exported `phase_pairs()` function.

**Comment by manchen07** [comment]
I think we can add `center` as an argument. What about `filter`? Should `preprocess_SCD()` allow users to filter some variables?

**Comment by jepusto** [comment]
Adding center would be good. I don't think we need the function to handle
filtering too. That can be done in a separate step using `dplyr::filter()`
or `subset()`.
