### ISSUE TITLE
refactor server.R

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#48]
Currently, there's a lot of redundancy in `server.R` between the code for model-fitting and ES estimation and the code to generate R syntax. Is there a way to re-factor and reduce redundancy, perhaps by storing some intermediate quantities in a `reactive()` object?

**Comment by jepusto** [comment]
Also, is it feasible to now use preprocess_SCD() in the data-cleaning steps within server?

**Comment by manchen07** [comment]
It is a great question. I'll take a look at this.
