### ISSUE TITLE
Can graphing functions use preprocess_SCD()?

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#53]
Check whether graphing functions can make use of new user-facing `preprocess_SCD()` function.

**Comment by manchen07** [comment]
For the `preprocess_SCD()` and `graph_SCD()` functions, do we want to allow "data = NULL" so that users can input a vector for case, session, etc? Currently, users must specify a data frame for `preprocess_SCD()`. The previous `graph_SCD()` allows data equal to NULL.

**Comment by jepusto** [comment]
Yes, I think it would be good to allow vector input.
