### ISSUE TITLE
Data with multiple outcomes for the same participant errors out

### ISSUE THREAD

**Issue by DMSwan** [jepusto/scdhlm#57]
The context for this is a multiple baseline design with three participants, and each participant has two outcomes that are measured simultaneously. My understanding is that using the filtering option, you should be able to select your preferred outcome and then estimate an effect size. Here's the correct setup on the load tab:

![image](https://user-images.githubusercontent.com/6385754/103016491-1b9d0280-4510-11eb-8b9d-a2aff0d26470.png)

However, using the version on shinyapps you just get an error trying to move on to the rest of the steps:

![image](https://user-images.githubusercontent.com/6385754/103016332-e395bf80-450f-11eb-844d-30a8813b7c65.png)

The same data/setup works just fine on the older version I have installed on my desktop (0.4.2.9300). The person who brought this to my attention has also successfully estimated this by putting it into separate data files and uploading them one by one.

I've attached the corresponding data:

[nazdat.xlsx](https://github.com/jepusto/scdhlm/files/5736119/nazdat.xlsx)

**Comment by jepusto** [comment]
﻿
Thanks for flagging this. I've reproduced the issue in versions 0.5.0 and 0.5.1. @manchen07, could you please take a look when you have the chance?

**Comment by jepusto** [comment]
@DMSwan I've pushed an update to shinyapps.io that should correct this. We will push an updated package to CRAN in the next week or so.
