### ISSUE TITLE
error handling when less than 3 cases

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#67]
Currently, the app throws multiple errors when there are less than three included cases. One of the errors is `"Error: invalid width or height value"`, which is probably a consequence of some graph formatting calculations that are based on the number of cases. I think we can suppress this error since we already display an error about the number of included cases. See D2UZ6IFU-1-2 in `Text reading fluency data per study.xlsx`.

**Comment by manchen07** [comment]
Could you let me know where I can find Text reading fluency data per study.xlsx file? Thanks!

**Comment by jepusto** [comment]
I just added it (on the main branch) under auxilliary.
