### ISSUE TITLE
Option of assuming level-1 error variance differs by treatment condition. 

### ISSUE THREAD

**Issue by jepusto** [jepusto/scdhlm#71]
In the web-app, provide option of assuming level-1 error variance differs by treatment condition
* Default to assuming homoskedasticity.
* Allow user to select a model with heteroskedastic level-1 error.

**Comment by manchen07** [comment]
It seems that this option can be added without relying on the `lmeInfo` updates?

**Comment by jepusto** [comment]
Put this option and the dependence structure options in a box called "Within-case error structure assumptions."
